config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :articles do
    resources :comments
    get :autocomplete_tag_name, :on => :collection
  end
  resources :tags
  resources :authors
  resources :author_sessions, only: [ :new, :create, :destroy ]
  
  get 'search', to: 'search#search'
  get 'signup' => 'authors#new'
  get 'login'  => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'
  root to: 'articles#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
require 'elasticsearch/model'
class Article < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings
  has_many :comments, :dependent => :destroy
  acts_as_taggable_on :tags

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

=begin
  def tag_list
    self.tags.collect do |tag|
      tag.name
    end.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end
=end
end

# Article.import force: true

app/models/author.rb
class Author < ApplicationRecord
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  has_many :taggings
  has_many :ratings, as: :rateable
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :articles, through: :taggings

  def to_s
    name
  end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :get_recent_articles

  private
  def get_recent_articles
    @recent_articles = Article.where('created_at >= ?', 1.week.ago).order('id desc').limit(7)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  autocomplete :tag, :name
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to article_path(@article)
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)

    redirect_to article_path(@article)
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comment.article_id = @article.id
  end

  private
  def article_params
    params.require(:article).permit(:title, :body, :tag_list, :image)
  end
end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController
  def new
  end

  def create
    if login(params[:email], params[:password])
      redirect_back_or_to(articles_path, notice: 'Logged in successfully.')
    else
      flash.now.alert = "Login failed."
      render action: :new
    end
  end

  def destroy
    logout
    redirect_to(:authors, notice: 'Logged out!')
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  #before_filter :zero_authors_or_authenticated, only: [:new, :create]

  def zero_authors_or_authenticated
    unless current_user
      redirect_to root_path
      return false
    end
  end

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)
    respond_to do |format|
      if @author.save
        login(params[:author][:email], params[:author][:password])
        format.html { redirect_to articles_path, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]

    @comment.save

    redirect_to article_path(@comment.article)
  end

  def comment_params
    params.require(:comment).permit(:author_name, :body)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search
    if params[:q].nil?
      @articles = []
    else
      @articles = Article.search(params[:q]).records
    end
	#redirect_to search_path
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    @tag = Tag.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<!-- First Comment -->
<article class="row">
  <div class="col-md-2 col-sm-2 hidden-xs">
    <figure class="thumbnail">
      <img class="img-responsive" src="http://www.keita-gaming.com/assets/profile/default-avatar-c5d8ec086224cb6fc4e395f4ba3018c2.jpg"/>
      <figcaption class="text-center"><%= comment.author_name %></figcaption>
    </figure>
  </div>
  <div class="col-md-10 col-sm-10">
    <div class="panel panel-default arrow left">
      <div class="panel-body">
        <header class="text-left">
          <!--<div class="comment-user"><i class="fa fa-user"></i> That Guy</div>-->
          <time class="comment-date" datetime="16-12-2014 01:05"><i class="fa fa-clock-o"></i> Dec 16, 2014</time>
        </header>
        <div class="comment-post">
          <p>
            <%= comment.body %>
          </p>
        </div>
        <p class="text-right"><a href="#" class="btn btn-default btn-sm"><i class="fa fa-reply"></i> reply</a></p>
      </div>
    </div>
  </div>
</article>
<!-- Second Comment Reply -->
<!--
<article class="row">
  <div class="col-md-2 col-sm-2 col-md-offset-1 col-sm-offset-0 hidden-xs">
    <figure class="thumbnail">
      <img class="img-responsive" src="http://www.keita-gaming.com/assets/profile/default-avatar-c5d8ec086224cb6fc4e395f4ba3018c2.jpg"/>
      <figcaption class="text-center">username</figcaption>
    </figure>
  </div>
  <div class="col-md-9 col-sm-9">
    <div class="panel panel-default arrow left">
      <div class="panel-heading right">Reply</div>
      <div class="panel-body">
        <header class="text-left">
          &lt;!&ndash;<div class="comment-user"><i class="fa fa-user"></i> That Guy</div>&ndash;&gt;
          <time class="comment-date" datetime="16-12-2014 01:05"><i class="fa fa-clock-o"></i> Dec 16, 2014</time>
        </header>
        <div class="comment-post">
          <p>comment text
          </p>
        </div>
        <p class="text-right"><a href="#" class="btn btn-default btn-sm"><i class="fa fa-reply"></i> reply</a></p>
      </div>
    </div>
  </div>
</article>
-->

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
    <ul>
      <% @article.errors.full_messages.each do |error| %>
          <li><%= error %></li>
      <% end %>
    </ul>
    <p>
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :body %><br />
      <%#= f.simplemde_text_area :body %>
      <%= f.cktext_area :body%>
    </p>
    <p>
      <%= f.label :tag_list %><br />
      <%= f.autocomplete_field :tag_list, autocomplete_tag_name_articles_path, :"data-delimiter" => ', ' %>
      <%#= f.collection_select :tag_list, Tag.order(:name), :id, :name, {}, {multiple: true} %>
    </p>
    <p>
      <% if @article.image.exists? %>
          <%= image_tag @article.image.url %><br/>
      <% end %>
      <%= f.label :image, "Attach a New Image" %><br />
      <%= f.file_field :image %>
    </p>
    <p>
      <%= f.submit %>
    </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Create a New Article</h1>
<%= render partial: 'form' %>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
<h1 class="page-header">
  <%= article.title%>
  <small>Secondary Text</small>
</h1>

<!-- First Blog Post -->
<h2>
  <a href="#">Blog Post Title</a>
</h2>
    <%= raw article.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
    <ul class="tags">
      <li><a href="#" class="tag">HTML</a></li>
      <li><a href="#" class="tag">CSS</a></li>
      <li><a href="#" class="tag">JavaScript</a></li>
    </ul>
<p><span class="glyphicon glyphicon-time"></span> Posted on August 28, 2013 at 10:00 PM</p>
<hr>
<img class="img-responsive" src="http://placehold.it/900x300" alt="">
<hr>
<p><%= article.body%></p>
<a class="btn btn-primary" href="#">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>

<hr>
<% end %>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>
<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.body.html_safe %></p>
<%= image_tag @article.image.url(:medium) %>
<%#= link_to "edit", edit_article_path(@article) %>
<%#= link_to "delete", article_path(@article),
            data: {confirm: "Really delete the article?"} ,
            method: :delete %>

<%#= link_to "<< Back to Articles List", articles_path %>
<p>
  Tags:
  <% @article.tags.each do |tag| %>
      <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>
<%if @article.comments.size > 0%>
<h2 class="page-header">Comments</h2>
<section class="comment-list">
<%= render partial: 'articles/comment', collection: @article.comments %>
</section>
<%end%>
<%= render partial: 'comments/form' %>

app/views/authors/_form.html.erb
<section class="form-horizontal">
  <fieldset>


    <!-- Text input-->
    <%= form_for(author) do |f| %>
        <% if author.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

              <ul>
                <% author.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>
        <div class="form-group">
          <label class="col-md-2 control-label" for="textinput">Username</label>
          <div class="col-md-6">
            <%= f.text_field :username, class: 'form-control input-md',placeholder: "Username", required: true  %>
          </div>
        </div>

        <div class="form-group">
          <label class="col-md-2 control-label" for="textinput">Email</label>
          <div class="col-md-6">
            <%= f.text_field :email, class: 'form-control input-md',placeholder: "Email", required: true  %>
          </div>
        </div>

        <div class="form-group">
          <label class="col-md-2 control-label" for="textinput">Password</label>
          <div class="col-md-6">
            <%= f.password_field :password, class: 'form-control input-md', required: true  %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-md-2 control-label" for="textinput">Password Confirmation</label>
          <div class="col-md-6">
            <%= f.password_field :password_confirmation, class: 'form-control input-md', required: true  %>
          </div>
        </div>

        <div class="form-group">
          <label class="col-md-2 control-label" for="comments"></label>
          <div class="col-md-6">
            <%= f.submit 'Submit' %>
          </div>
        </div>
    <%end%>
  </fieldset>
</section>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Password</th>
      <th>Password confirmation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.username %></td>
        <td><%= author.email %></td>
        <td><%= author.password %></td>
        <td><%= author.password_confirmation %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @author.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @author.password %>
</p>

<p>
  <strong>Password confirmation:</strong>
  <%= @author.password_confirmation %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/comments/_form.html.erb
<section class="form-horizontal">
  <fieldset>

    <!-- Form Name -->
    <legend>Post a Comments</legend>

    <!-- Text input-->
    <%= form_for [ @article, @comment ] do |f| %>
    <div class="form-group">
      <label class="col-md-2 control-label" for="textinput">Name</label>
      <div class="col-md-6">
        <%= f.text_field :author_name, class: 'form-control input-md',placeholder: "Name", required: true  %>
      </div>
    </div>

    <!-- Textarea -->
    <div class="form-group">
      <label class="col-md-2 control-label" for="comments">Comment</label>
      <div class="col-md-6">
        <%= f.text_area :body, class: "form-control"%>
      </div>
    </div>
        <div class="form-group">
          <label class="col-md-2 control-label" for="comments"></label>
          <div class="col-md-6">
            <%= f.submit 'Submit' %>
          </div>
        </div>
        <%end%>
  </fieldset>
</section>

app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.articles.each do |article| %>
      <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>